version: "3.8"

services:
    postgres-db:
        image: postgres:15
        container_name: postgres-db
        restart: always
        environment:
            POSTGRES_DB: alerta_apagao_db
            POSTGRES_USER: alerta_user
            POSTGRES_PASSWORD: alerta_password
        ports:
            - "5433:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
    db-data:
