
package com.alertaApagao.monitoringService.stub_classes;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "AlertService", targetNamespace = "http://alertaApagao.com.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AlertService {


    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://alertaApagao.com.br/AlertService/sendSMSRequest", output = "http://alertaApagao.com.br/AlertService/sendSMSResponse")
    public void sendSMS(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
