
package com.alertaApagao.monitoringService.stub_classes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AlertServiceImplementationService", targetNamespace = "http://alertaApagao.com.br/", wsdlLocation = "http://localhost:8085/AlertService?wsdl")
public class AlertServiceImplementationService
    extends Service
{

    private static final URL ALERTSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException ALERTSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private static final QName ALERTSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://alertaApagao.com.br/", "AlertServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/AlertService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALERTSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        ALERTSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public AlertServiceImplementationService() {
        super(__getWsdlLocation(), ALERTSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public AlertServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALERTSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public AlertServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, ALERTSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public AlertServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALERTSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public AlertServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlertServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlertService
     */
    @WebEndpoint(name = "AlertServiceImplementationPort")
    public AlertService getAlertServiceImplementationPort() {
        return super.getPort(new QName("http://alertaApagao.com.br/", "AlertServiceImplementationPort"), AlertService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertService
     */
    @WebEndpoint(name = "AlertServiceImplementationPort")
    public AlertService getAlertServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://alertaApagao.com.br/", "AlertServiceImplementationPort"), AlertService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALERTSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw ALERTSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return ALERTSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
